language: node_js
node_js:
  - 14
cache: npm
branches:
  only:
    - blog # build master branch only
script:
  - hexo clean
  - hexo generate
install: # 解决yarn报错问题
    - yarn
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: blog
  local-dir: public
