language: node_js
node_js:
  - 12
cache: npm
branches:
  only:
    - blog # build master branch only
script:
  - hexo generate
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: blog
  local-dir: public
